### ISSUE TITLE
Laravel 5.6 support

### ISSUE THREAD

**Issue by renedekat** [austinheap/laravel-database-encryption#10]
Could you update the composer file to allow for Laravel 5.6 and tag a new release?

**Comment by austinheap** [comment]
Hey @renedekat, I added `5.6.*` support here: https://github.com/austinheap/laravel-database-encryption/commit/98085573a279f16759dd9f9a24f4cf64c12ac00f

I haven't personally tested it (and the unit tests don't target it [yet]) so let me know how it goes!

**Comment by renedekat** [comment]
It works fine for me in a live 5.6 project.

**Comment by austinheap** [comment]
Closing this out unless/until others report issues w Laravel `5.6.*`.
