### ISSUE TITLE
Cannot Disable Encryption globally via DATABASE_ENCRYPTION_ENABLED variable

### ISSUE THREAD

**Issue by JustinGT** [austinheap/laravel-database-encryption#11]
Tried this on a fresh install of laravel 5.5.*

the environment var (in `.env`) `DATABASE_ENCRYPTION_ENABLED=false` is ignored.

so if I want to disable the encryption i have to comment out the `use HasEncryptedAttributes;` statement in each model.

**Comment by austinheap** [comment]
Thanks for reporting this @JustinGT, I'll have time in the next week~ to look into this.

**Comment by austinheap** [comment]
@JustinGT just pushed a fix and `README.md` updated in https://github.com/austinheap/laravel-database-encryption/commit/026d7b999bfa2a003ace2e23a25d67a0bcce0c9a. The corrected environment variable to set is `DB_ENCRYPTION_ENABLED`, not `DATABASE_ENCRYPTION_ENABLED` like the docs erroneously stated. Let me know if you run into any issues.

**Comment by JustinGT** [comment]
Yes, can confirm that this has resolved the problem.
