### ISSUE TITLE
Unchanged attributes are re-encrypted

### ISSUE THREAD

**Issue by MarkTierney1975** [austinheap/laravel-database-encryption#12]
Hi, not sure if this is a bug or intentional?

When I update a model unchanged attributes are re-encrypted. Could/should there be a comparison with the saved unencrypted value first and only encrypt if they are different?

**Comment by MarkTierney1975** [comment]
I have been overriding the originalIsEquivalent function, not sure if this is the best approach though.

`/**
     * Determine if the new and old values for a given key are equivalent.
     *
     * @param  string $key
     * @param  mixed  $current
     * @return bool
     */
    protected function originalIsEquivalent($key, $current)
    {
        if (! array_key_exists($key, $this->original)) {
            return false;
        }

        $original = $this->getOriginal($key);
        
        // Get unencrypted values to compare.
        if (isset($this->encrypted) && is_array($this->encrypted) && in_array($key, $this->encrypted)) {
            $current = $this->decryptedAttribute($current);
            $original = $this->decryptedAttribute($this->getOriginal($key));
        }

        if ($current === $original) {
            return true;
        } elseif (is_null($current)) {
            return false;
        } elseif ($this->isDateAttribute($key)) {
            return $this->fromDateTime($current) ===
                   $this->fromDateTime($original);
        } elseif ($this->hasCast($key)) {
            return $this->castAttribute($key, $current) ===
                   $this->castAttribute($key, $original);
        }

        return is_numeric($current) && is_numeric($original)
                && strcmp((string) $current, (string) $original) === 0;
    }`

**Comment by austinheap** [comment]
@MarkTierney1975 Were you able to confirm this bug? I only ask because I saw you closed the issue. If so, pull requests are welcome! 🎉

**Comment by MarkTierney1975** [comment]
Hi Austin, I’m a total Github noob and I closed it by accident! I’m not 100% sure it’s a bug yet as I found some mistakes in my application. I’ll double check tomorrow and update accordingly. Cheers 🙂

**Comment by MarkTierney1975** [comment]
I'm fairly sure this is a bug after looking at it again.

**Comment by MarkTierney1975** [comment]
Hi Austin, did you ever look into this? This is a bug and it means this package cannot be used in conjunction with a revision package as every time a model is save all attributes are re-encrypted.

The Laravel default behaviour is to only update attributes that have been changed.

**Comment by austinheap** [comment]
Hey @MarkTierney1975 -- it's not feasible for me to guarantee interoperability between random packages out there.

Feel free to re-open if you can reproduce this behaviour _without other packages_.
