### ISSUE TITLE
Your package is only working elequent not with Query builder. Is there any way for query builder?

### ISSUE THREAD

**Issue by dhirender027** [austinheap/laravel-database-encryption#15]
Hi,

I am just trying your package to that, is it fullfilling my requirement. Yes, your package is working but only elequent. I have used query builder in some of place in my project to reduce the page load time as well as relationship queries.

Your package is not compatible with query builder. Is there any way to make compatible it with query builder?

Thanks

**Comment by austinheap** [comment]
Hi @dhirender027, this package is only intended to support Eloquent. Encryption of Query builder calls is outside the scope of this project.
