### ISSUE TITLE
Upgrading from dev-master 4ce8e8c to dev-master b5f9b05 breaks decryption of existing data

### ISSUE THREAD

**Issue by zero0cool0** [austinheap/laravel-database-encryption#22]
After performing a composer update this morning, existing encrypted data is not properly decrypted anymore. All I'm getting are long strings that begin with "__LARAVEL-DATABASE-ENCRYPTED-VERSION-00-01-00__versionVERSION-00-01-"

Is this meant to be backwards compatible or do I have to reencrypt everything?

**Comment by austinheap** [comment]
@zero0cool0 Were you able to find a solution? I still need to test the upgrade mechanism before releasing the new version that in dev-master-b5f9b05, so keen to know how it went for you!

**Comment by zero0cool0** [comment]
I wasn't really able to find a solution and closed the issue because I assumed it wasn't backwards compatible. 
My current workaround is to use release 0.1.1. I had originally checked out dev-master because I'm using Laravel 5.6 and release 0.1.0 as mentioned in the docs requires Laravel 5.5.
