### ISSUE TITLE
Cant put the encrypted field in the database

### ISSUE THREAD

**Issue by BramKlapwijk** [austinheap/laravel-database-encryption#23]
When i want to seed the encrypted field in the database it sais:

SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'first_name' at row 1

Where can i set the length of the encrypted string

**Comment by austinheap** [comment]
See the [Schemas](https://github.com/austinheap/laravel-database-encryption#schemas) section of the [`README.md`](https://github.com/austinheap/laravel-database-encryption/blob/master/README.md) for information on proper column types. If something is getting truncated, it's likely that the column type is `VARCHAR` and isn't big enough to store the encrypted value.
