### ISSUE TITLE
Laravel 5.7.* compatability

### ISSUE THREAD

**Issue by t2thec** [austinheap/laravel-database-encryption#27]
Hey, thanks so much for putting this package together. There is requirement of Laravel 5.5.* with this package.

Do you have any current plans on bumping this? if so any ETA?

If we were to make a PR - do you think it should be a quick win? Or are there likley to be issues?

Many thanks, looking forward to using it - Really nicely put together.

**Comment by cbzink** [comment]
Looking through the breaking changes for 5.7, there's not a whole lot of DB-related changes and it doesn't look like any of them should affect laravel-database-encryption. Should hopefully be an easy patch!

**Comment by austinheap** [comment]
@t2thec Only one way to find out! Feel free to make a PR. The unit tests will either be happy -- and I'm happy to cut a draft release -- or they'll barf and it'll be a bit more work.

**Comment by t2thec** [comment]
Great. Thanks guys. I’ll take a look over the next few days and get a PR in. 

Cheers.
