### ISSUE TITLE
Add support for Laravel 5.7

### ISSUE THREAD

**Issue by axelitus** [austinheap/laravel-database-encryption#28]
Currently this package cannot be installed with Laravel 5.7 due to the restriction:

```
"require": {
    "laravel/framework": "5.5.*|5.6.*",
}
```

Please add support for Laravel 5.7

**Comment by austinheap** [comment]
Feedback please: https://github.com/austinheap/laravel-database-encryption/commit/573112a53089d7b946005b6f65385bfebbb07138. 😁

**Comment by austinheap** [comment]
@axelitus Good catch! Fixed in commit: https://github.com/austinheap/laravel-database-encryption/commit/33db743da6b24c7d72ea61385a850b2aed69c9fb

**Comment by axelitus** [comment]
I found an issue with the commit [573112a](https://github.com/austinheap/laravel-database-encryption/commit/573112a53089d7b946005b6f65385bfebbb07138), the encrypted fields are being correctly generated but an unencrypted value is being stored in the database.

I've debugged the code and the issue is related to [this change](https://github.com/laravel/framework/commit/c5401623dcb8eb3b7511c821c60d97427579cac5) introduced 21 days ago (which in fact breaks support for Laravel 5.6 also).

Previously, on insert the `$this->attributes` property was used directly, now `$this->getAtttributes()` method is called, which in fact is replaced by the [HasEncryptedAttributes trait](https://github.com/austinheap/laravel-database-encryption/blob/master/src/Traits/HasEncryptedAttributes.php) and [this line](https://github.com/austinheap/laravel-database-encryption/blob/573112a53089d7b946005b6f65385bfebbb07138/src/Traits/HasEncryptedAttributes.php#L321) gets executed which unencrypts all attribute values before insert.

The result is that the package "is broken" because it doesn't achieve it's purpose.

My proposal is to change the `getAttributes()` method to `getUnencryptedAttributes()` and use the LAravel implementation directly, but I'm not sure if the `getAttributes()` is used elsewhere that needs to be changed.

**Comment by austinheap** [comment]
@axelitus Can you make a separate issue for this and include code to reproduce the bug? Without digging in too much, this seems accurate and would explain other oddities in the when using non-5.5. (Lesson learned on accepting pull requests for new Laravel versions... 😞)

**Comment by axelitus** [comment]
I'll open an issue later on with a use case

**Comment by austinheap** [comment]
Closing in lieu of https://github.com/austinheap/laravel-database-encryption/issues/30.
