### ISSUE TITLE
Not encrypting files on storing/creating db record 

### ISSUE THREAD

**Issue by TechTailor** [austinheap/laravel-database-encryption#31]
Hey, 

The records are not being encrypted when I am creating/storing new info in the database, but on UPDATE action they are being encrypted. Dont know what I am doing wrong here but would help any guidance.

Thanks.

**Comment by axelitus** [comment]
This issue seems to be a duplicate of #30

**Comment by TechTailor** [comment]
Issue fixed in pr #32
