### ISSUE TITLE
Doesn't work with Laravel 5.7

### ISSUE THREAD

**Issue by Kingmaddi** [austinheap/laravel-database-encryption#33]
Hello,

i have a problem. I installed the plugin with Laravel 5.7. I have inserted 

`use AustinHeap\Database\Encryption\Traits\HasEncryptedAttributes;  `

on top of my Model and defined 

```
 use HasEncryptedAttributes;

 protected $encrypted = [
        'name',
 ];
```

in it. But after saving the Model in the Database, the Attribute _name_ doesn't encrypted. 
Are there any ideas to fix it?

Thank you for your help

**Comment by austinheap** [comment]
Hi @Kingmaddi -- this package does not currently support Laravel 5.7.x.
