### ISSUE TITLE
No Encryption then Create new Model instance

### ISSUE THREAD

**Issue by Kingmaddi** [austinheap/laravel-database-encryption#35]
Hi,

then I create a new Model, for example a new User, and save it to the Database, the attributes are not encrypted. Then I overwrite some attributes from this Modal and save the updated Model in the database, the updated attributes are encrypted.

How I can fix this?

Thank you

**Comment by austinheap** [comment]
Dupe of https://github.com/austinheap/laravel-database-encryption/issues/30
