### ISSUE TITLE
firstOrCreate() only encrypts properties in first parameter--not second.

### ISSUE THREAD

**Issue by dclaysmith** [austinheap/laravel-database-encryption#39]
firstOrCreate() takes a second parameter--a list of attributes to be applied to model that is found or created: https://laravel.com/docs/5.5/eloquent

$flight = App\Flight::firstOrCreate(
    ['name' => 'Flight 10'], ['delayed' => 1]
);

In this case, "delayed" would not be encrypted.

**Comment by austinheap** [comment]
Closing: zero technical context. Feel free to re-open w a repro case.
