### ISSUE TITLE
New Version of paragonie/random_compat

### ISSUE THREAD

**Issue by Nowi5** [austinheap/laravel-database-encryption#41]
Hi,

can you please check if we can update to the new version of random_compat?

Thank you.

**Comment by 749** [comment]
If I read the docs of https://packagist.org/packages/paragonie/random_compat correctly, it is not necessary to be required at all when using php >= 7.1. random_compat is only required to get the new random functions from php7 in php5.
Please fix this, as the package can currently not be installed anymore!

**Comment by toddhulsman** [comment]
I was able to fix this.  I don't know if this is the preferred way to correct it, but here are the steps I took:

1. edit composer.json to require:
"paragonie/random_compat": "2.*"

2. Run composer update from command line.

3. Re-run composer require austinheap/laravel-database-encryption

Installed just fine for me when I took those steps.
