### ISSUE TITLE
Laravel 5.8 support

### ISSUE THREAD

**Issue by vladshoob** [austinheap/laravel-database-encryption#46]
Thanks for package and good work.

We need to update the package to support Laravel 5.8. Probably there might be some not-compabilities.

**Comment by edgrosvenor** [comment]
It looks like there's a pull request already to handle this.

**Comment by toddhulsman** [comment]
Any updates on this?  I'm in the same boat with needing to install this on version 5.8.  Thanks!

**Comment by stickeegreg** [comment]
For now, you can `composer require mckibbe/laravel-database-encryption "dev-master#b664138259083dde56b4e718962ece5e26b81933"`

**Comment by cypriotxx** [comment]
[happy2let@sharedserver10 public_html]$ php -d memory_limit=-1 composer.phar require austinheap/laravel-database-encryption
Using version ^0.2.0 for austinheap/laravel-database-encryption
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for austinheap/laravel-database-encryption ^0.2.0 -> satisfiable by austinheap/laravel-database-encryption[v0.2.0].
    - Conclusion: remove laravel/framework v5.8.17
    - Conclusion: don't install laravel/framework v5.8.17
    - austinheap/laravel-database-encryption v0.2.0 requires laravel/framework 5.5.*|5.6.*|5.7.* -> satisfiable by laravel/framework[5.5.x-dev, 5.6.x-dev, 5.7.x-dev].
    - Can only install one of: laravel/framework[5.6.x-dev, v5.8.17].
    - Can only install one of: laravel/framework[5.7.x-dev, v5.8.17].
    - Can only install one of: laravel/framework[5.5.x-dev, v5.8.17].
    - Installation request for laravel/framework (locked at v5.8.17, required as 5.8.*) -> satisfiable by laravel/framework[v5.8.17].


Installation failed, reverting ./composer.json to its original content.
[happy2let@sharedserver10 public_html]$ php -d memory_limit=-1 composer.phar require mckibbe/laravel-database-encryption "dev-master#b664138259083dde56b4e718962ece5e26b81933"


  [InvalidArgumentException]
  Could not find a matching version of package mckibbe/laravel-database-encryption. Check the package spelling, your version c
  onstraint and that the package is available in a stability which matches your minimum-stability (dev).


require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--update-with-all-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...


what do we do please ? thnx

**Comment by katieben** [comment]
@stickeegreg, I tried that on Laravel 5.8 and got this error:

[InvalidArgumentException]                                                   
  Could not find a matching version of package mckibbe/laravel-database-encry  
  ption. Check the package spelling, your version constraint and that the pac  
  kage is available in a stability which matches your minimum-stability (dev)  
  .

**Comment by stickeegreg** [comment]
@katieben I edited my comment above - try that

**Comment by katieben** [comment]
@stickeegreg Thanks! Getting closer, it's down to this now: 

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for mckibbe/laravel-database-encryption dev-master#b664138259083dde56b4e718962ece5e26b81933 -> satisfiable by mckibbe/laravel-database-encryption[dev-master].
    - Conclusion: remove paragonie/random_compat v9.99.99
    - Conclusion: don't install paragonie/random_compat v9.99.99
    - mckibbe/laravel-database-encryption dev-master requires paragonie/random_compat ^2.0 -> satisfiable by paragonie/random_compat[v2.0.0, v2.0.1, v2.0.10, v2.0.11, v2.0.12, v2.0.13, v2.0.14, v2.0.15, v2.0.16, v2.0.17, v2.0.18, v2.0.2, v2.0.3, v2.0.4, v2.0.5, v2.0.6, v2.0.7, v2.0.8, v2.0.9].
    - Can only install one of: paragonie/random_compat[v2.0.0, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.1, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.10, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.11, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.12, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.13, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.14, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.15, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.16, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.17, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.18, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.2, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.3, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.4, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.5, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.6, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.7, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.8, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.9, v9.99.99].
    - Installation request for paragonie/random_compat (locked at v9.99.99) -> satisfiable by paragonie/random_compat[v9.99.99].


Installation failed, reverting ./composer.json to its original content.

**Comment by lanort** [comment]
As this package seems to be abandoned, I am now using this lightweight approach: https://laracasts.com/discuss/channels/laravel/encrypting-model-data

**Comment by RobertCordes** [comment]
If this package is indeed abandoned I think I’m screwed. I really hope @austinheap will find some time to update the package. 👍

**Comment by jangrimm** [comment]
@RobertCordes I forked the package awhile ago and implemented L5.8 compatibility. Works in a number of production systems, all good. I'll also keep care of the package in my repo. It's not available via Packagist, though.

**Comment by RobertCordes** [comment]
@jangrimm Thanks. Right now I'm using the fork from @mckibbe (https://github.com/mckibbe/laravel-database-encryption). Still, with this kind of core functionality it would be nice to have the _original_ repo under active development. Not that I can think of any missing functionality :) But it would be nice to at least hear from @austinheap that this repo isn't completely abandoned. Otherwise there's always this feeling that some day things can go south. Maybe that's just me though.

**Comment by austinheap** [comment]
@jangrimm PRs are welcome.

**Comment by austinheap** [comment]
@jangrimm PRs are welcome.

@RobertCordes Not abandoned by any stretch. I'm not interested in accepting PRs that can't pass compliance, though. Apologies if that came off the wrong way.

**Comment by RobertCordes** [comment]
Hey @austinheap I’m so glad you’re still working on the project 😅 thanks!
