### ISSUE TITLE
Cannot decrypt model attribute with no package header! Error

### ISSUE THREAD

**Issue by edwink75** [austinheap/laravel-database-encryption#47]
I'm able to encrypt the data, an encryption header is written, but it's not detected by the plugin.
If i use the normal getter i.e. $user->name or $user->getAttribute('name'), I get the encrypted string in return.
`\u0001\u0002__LARAVEL-DATABASE-ENCRYPTED-VERSION-00-01-02__\u0003\u001eversion\u0019VERSION-00-01-02\u0017\u001etype\u0019string[native]\u0017\u0004eyJpdiI6IlJndER1VWQ4ek1PVGhSRk5MRjNwWGc9PSIsInZhbHVlIjoiMXR1`

if I use $user->decryptedAttribute('name'), I get the above message.
I can see that the system is looking for the wrong start and end for the header:

`array:2 [▼
  "start" => array:3 [▼
    "int" => 1
    "string" => "\x01"
    "default" => true
  ]
  "stop" => array:3 [▼
    "int" => 4
    "string" => "\x04"
    "default" => true
  ]
]`

but overriding this values with \u0001 and \u001e didn't make a difference

My db config is standard:
` 'mysql' => [
            'driver'    => 'mysql',
            'host'      => env('DB_HOST', 'localhost'),
            'database'  => env('DB_DATABASE', 'forge'),
            'username'  => env('DB_USERNAME', 'forge'),
            'password'  => env('DB_PASSWORD', ''),
            'charset'   => 'utf8',
            'collation' => 'utf8_unicode_ci',
            'prefix'    => '',
            'strict'    => false,
        ],`

**Comment by edwink75** [comment]
Problem found: **All encrypted fields need to be changed to datatype TEXT on database level**

This should be added to the documentation in **FAT**

**Comment by RobertCordes** [comment]
All my encrypted fields have the datatype TEXT and I still get this error :-/
