### ISSUE TITLE
Is there a way to encrypt old-unencrypted data?

### ISSUE THREAD

**Issue by filipac** [austinheap/laravel-database-encryption#55]
I added this package after i already had data in database, so I am looking to encrypt old data. I was initially thinking of updating updated_at and saving the model and it would encrypt, but it does not cause the encrypted attribute is not considered dirty. Any idea/hint on how i might encode old data?

**Comment by roelofr** [comment]
You'd have to trick Laravel into thinking the current value isn't the current value. 

Luckily, there's a method you can (ab)use for that.

```php
$prefix = AustinHeap\Database\Encryption\EncryptionFacade::getPrefix();
$query = App\MyModel::where('encrypted_field', 'not like', "{$prefix}%")->cursor();

foreach ($query as $row) {
    // Move value into memory
    $tempField = $row->encrypted_field;

    // Clear field and tell Laravel that's normal
    $row->encrypted_field = null;
    $row->syncOriginalAttributes('encrypted_field');

    // Reset field
    $row->encrypted_field = $tempField;

    // Save "changes"
    $row->save(['encrypted_field']);
}
```

**Disclaimer**: This is untested code, Your Mileage May Vary.
