### ISSUE TITLE
Trait 'App\HasEncryptedAttributes' not found

### ISSUE THREAD

**Issue by schonhose** [austinheap/laravel-database-encryption#8]
So, I am trying to upgrade my laravel 5.1 install with Elocrypt towards laravel 5.5. Currently I am trying this package to see if it can encrypt and decrypt my old database.

In order to do so, I followed the installation instructions in the readme and made the following changes to the config.
```
'enabled'            => env('DB_ENCRYPTION_ENABLED', true),
'prefix'             => env('DB_ENCRYPTION_PREFIX', '__ELOCRYPT__'),
'versioning'         => env('DB_ENCRYPTION_VERSIONING', false),
```

I modified my user.php model:

```
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use AustinHeap\Database\Encryption;

class User extends Authenticatable
{
    use Notifiable;
    use HasEncryptedAttributes;

    protected $encrypted = [
        'name'
    ];
}
```

However, running this code gives me the `Trait 'App\HasEncryptedAttributes' not found`. I am sure I am missing something here, but what?

**Comment by austinheap** [comment]
Hey there @schonhose -- make sure you have `use AustinHeap\Database\Encryption\HasEncryptedAttributes;` at the top of your user model. I haven't tried a direct migration from Elocrypt to this yet, so let me know how it goes!

**Comment by schonhose** [comment]
Hey @austinheap -- I tried using `use AustinHeap\Database\Encryption\HasEncryptedAttributes;` but I got the `Trait 'AustinHeap\Database\Encryption\HasEncryptedAttributes' not found` error

I tried different combinations, but it just won't work. I even registered the service provider and the class alias in the `app.php` just to make sure.

A `composer update` does not update the package, so I am a bit baffled by this.

**Comment by schonhose** [comment]
I delved into the code, and it seems the correct way to use the trait would be: `use AustinHeap\Database\Encryption\Traits\HasEncryptedAttributes;`. With this the error disappears.

However, using an eloquent query does not automatically decrypt the values. This has probably to do with the following from the readme:

> By including the HasEncryptedAttributes trait, the setAttribute() and getAttributeFromArray() methods provided by Eloquent are overridden to include an additional step. This additional step simply checks whether the attribute being accessed via setter/getter is included in the $encrypted array on the model, and then encrypts or decrypts it accordingly.

The `user` model in my case does not extends Eloquent, but `Authenticatable`.

Anyway, I dug in a little deeper and tried to manually decrypt the value using 

```
$user->name = $user->decryptedAttribute($user->name);
```

but this gives me the following error on line 171 of the trait: `Type error: substr() expects parameter 2 to be integer, boolean given`.

So, I dug myself into an even bigger hole by performing the following code:

```
        $test = str_replace("__ELOCRYPT__:", "", $user->name);
        $test = \Crypt::decrypt($test);
        dd($test);
```

This successfully decrypts my string to the original values. Hope this helps.

**Comment by schonhose** [comment]
Any idea on solving the `Trait 'App\HasEncryptedAttributes' not found` error? I am still stuck on this.

**Comment by austinheap** [comment]
Hey @schonhose -- I haven't been able to replicate the bug on my side. I make a new Laravel 5.5 project, install with composer, and then it works. It's also passing the unit tests which have 100% code coverage.

Can you give me a file I can replicate the bug with?

**Comment by schonhose** [comment]
Hey @austinheap, I have send you an email last week asking for more details what you would like to have from me.

**Comment by ITwrx** [comment]
same here. i just updated from 5.2->5.3->5.4->5.5 and uninstalled elocrypt and installed this package. copying the readme got me the same results as @schonhose. now i have 

```
use AustinHeap\Database\Encryption;
use AustinHeap\Database\Encryption\Traits\HasEncryptedAttributes;
```

at the top of my model with 

```
use HasEncryptedAttributes;
```
inside the class. The error is gone but the data is not decrypted. I notice that the existing data has the "ELOCRYPT" prefix so maybe this is the cause? Is going back to elocrypt (and whatever laravel version it supported) and decrypting the data prior to replacing elocrypt(or manually decrypting as shown above), the only route for upgrading between these two packages? i notice elocrypt had the option to set the prefix used. does this package retain this option? if so, i could theoretically use this option to hack my app back to functionality if it were documented/pointed out.

thanks

**Comment by austinheap** [comment]
@ITwrx As you noticed, the prefixes that Elocrypt uses are not compatible with this package -- so there currently is no direct migration path from Elocrypt to laravel-database-encryption. Pull requests are welcome but for now you need to decrypt any data encrypted by Elocrypt, remove it, then install this package.

I'll add a note to the docs about this.

**Comment by austinheap** [comment]
Migration instructions added to FAQ in `README.md`: https://github.com/austinheap/laravel-database-encryption/tree/d99bffc1c7c7130c2e22c77b851adc49a3a8d700#is-this-package-compatible-with-elocryptfive-out-of-the-box

As mentioned, pull requests are welcome to automate this process! 🎉

**Comment by ITwrx** [comment]
thanks for the docs. trying to automate it sounds fun, but i don't know if it will ever make it to the top of my list either. :)
