### ISSUE TITLE
min required PHP version

### ISSUE THREAD

**Issue by kingvish** [austinheap/laravel-database-encryption#9]
Hi There,
This package has min required PHP 7.1.0, Laravel 5.5 itself has min required PHP 7.0.0. Can this package use for 7.0?

Thanks

**Comment by austinheap** [comment]
Hey @kingvish -- this package uses [nullable types](http://php.net/manual/en/migration71.new-features.php) which are only available in PHP 7.1.0+, so it will not work with older versions of PHP without modifying the source.
